#cloud-config
users:
  - name: ubuntu
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD12gl+9j97E60/7K5DQ4zdRlOALTSc0adIb59CJaNIhrSLlmPkJ7lgpPUV3cfqj8OXtyEUKlsYozy6McRHj42vPgYwwBCc+H69fN0DaThizhdlt5DyqbpUbWeIHGG4OHTqB2CY9bHn11ofBhSLPL4NU6BwnLOy7z5o4Gp7PCOBfj/Bq4EUyIzfACn7L4ow0JBYgON/3dvzGidAHWdJXFuhOZs1V+Fswlcrz1rLLPFTUutNhtr9Q0CojGpCdQ3k4NSyztYXx1SKFfM8cG25X6xPqejmJNgsSSXjwgAP/gvDqRHG7Dp8eeiH0AP7xyNclIbQXyr/2bJe7ljMEpcJLMr/pVLu748K+Qo8U2GANhZS44PTrMI+YmOewDLVt/0WKBc48R3MTuQJgq0sK2qKCJKvVKFnghxXPCZfruKyRS6d1yw31zcgUPzY31ptIH8r7QiT/X+qtUBo9vAsZWmsVfS526JxyUBBOlzoa9qAyexh6fUFeKbDmdZLhdgKO47gkV1tj3BfFD+UqvHeM77ARaqfBGKDe25YNpNqAyLoxQYf3meSdo5HjWxo+HYkq9EO8HAk9jCwmXBfwVWldwXB0+pPLlr3hyWnXrrLJFYCdUTcK+aR5yBBLdlD3pNhKP6ki3rYqevx3ufkS83p4O2j5hDpmLm3nYnWHLsovrL0wM+Zrw== teo@teo-G3-3590

hostname: myvm
package_update: true
package_upgrade: true
packages:
  - sl

write_files:
   - path: /home/ubuntu/.vimrc
     defer: true
     content: |
        set laststatus=2
        set noshowmode
        let g:lightline = {
              \ 'colorscheme': 'wombat',
              \ 'active': {
              \   'left': [ [ 'mode', 'paste' ],
              \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
              \ },
              \ 'component_function': {
              \   'gitbranch': 'FugitiveHead'
              \ },
              \ }
        let g:lightline = {
              \ 'component_function': {
              \   'filename': 'LightlineFilename',
              \ },
              \ }

        let g:javascript_plugin_jsdoc = 1
        let g:vim_jsx_pretty_colorful_config = 1
        autocmd FileType javascript setlocal shiftwidth=2 tabstop=2
        autocmd FileType javascriptreact setlocal shiftwidth=2 tabstop=2

        function! LightlineFilename()
          return &filetype ==# 'vimfiler' ? vimfiler#get_status_string() :
                \ &filetype ==# 'unite' ? unite#get_status_string() :
                \ &filetype ==# 'vimshell' ? vimshell#get_status_string() :
                \ expand('%:t') !=# '' ? expand('%:t') : '[No Name]'
        endfunction
        let g:unite_force_overwrite_statusline = 0
        let g:vimfiler_force_overwrite_statusline = 0
        let g:vimshell_force_overwrite_statusline = 0
        set number
        set autoread
        set autoindent
        set cindent
        set hlsearch
        set incsearch
        set ignorecase
        set smartcase
        set mouse=a
        set shiftwidth=3
        nnoremap B ^
        nnoremap E $
        noh
        command! Config execute ":e $MYVIMRC"
        command! Reload execute "source ~/.vimrc"

        set nocompatible
        filetype off

   - path: /home/ubuntu/.bash_aliases
     defer: true
     content: |
        alias s="source ~/.bashrc"
        alias tasks='grep --exclude-dir=.git -rEI "TODO|FIXME" . 2>/dev/null'
        alias ..='cd ../'                           # Go back 1 directory level
        alias ...='cd ../../'                       # Go back 2 directory levels
        alias ....='cd ../../../'                   # Go back 3 directory levels
        alias .....='cd ../../../../'               # Go back 4 directory levels
   - path: /home/ubuntu/.gitconfig
     defer: true
     content: |
        [user]
        name = Teo Podobnik
        email = teo.podobnik1234@gmail.com

        [alias]
                c = commit
                a = add
                l = log
                s = status
                ca = commit --amend
        [core]
                editor = vim
